name: Run Bot

on:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Download
        uses: actions/checkout@v4

      - name: Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Run
        run: npm start
